version: '3.7'

services:
  db:
    build: postgres_init
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

  app:
    build: .
    restart: on-failure
    depends_on:
      - db
    ports:
      - '8000:8080'
    command: ["bash","./wait-for-it.sh", "db:5432", "--", "python3.6", "-u" ,"run.py"]
    env_file:
      - .env

  parser:
    build: .
    restart: on-failure
    depends_on:
      - db
    command: ["bash","./wait-for-it.sh", "db:5432", "--", "python3.6", "-u" ,"run_job.py"]
    env_file:
      - .env